name: Build and Push QingLong Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'QingLong/services.json'
      - 'QingLong/notify.py'
      - 'QingLong/front.conf'
      - 'QingLong/docker-entrypoint.sh'
      - 'QingLong/README.md'
      - 'QingLong/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./QingLong
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qinglong:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=QingLong Docker Image
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
